name: Deploy with Terraform

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  
jobs:
  deploy:
    uses: souzapablo/github-actions/.github/workflows/terraform-plan.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}

  apply:
    environment: production
    uses: souzapablo/github-actions/.github/workflows/terraform-apply.yml@main
    with:
      plan_run_id: ${{ github.event.inputs.plan_run_id }}
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }
 
