name: Deploy with Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  
jobs:
  deploy:
    uses: souzapablo/github-actions/.github/workflows/terraform-plan.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
 
