name: Deploy Infrastructure
on:
  pull_request:
    branches: [main]

jobs:
  terraform:
    uses: souzapablo/github-actions/.github/workflows/terraform.yml@main
    with:
      working-directory: "./infrastructure"
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    permissions:  # explicitly pass allowed permissions
      contents: read
      pull-requests: write
