name: Deploy with Terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    uses: souzapablo/github-actions/blob/main/.github/workflows/terraform.yml@main
    with:
      environment: production
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
