name: Deploy with Terraform
on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  
jobs:
  terraform:
    uses: souzapablo/github-actions/.github/workflows/terraform/main.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
