name: Deploy Infrastructure
on:
  pull_request:
    branches: [main]
jobs:
  terraform:
    environment: 'production'
    name: 'Infrastructure Deployment'
    uses: souzapablo/github-actions/.github/workflows/terraform.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    with:
      runners: '["ubuntu-latest", "ubuntu-22.04"]'
    permissions:  # explicitly pass allowed permissions
      contents: read
      pull-requests: write
