name: Deploy Infrastructure
on:
  pull_request:
    branches: [main]
jobs:
  terraform:
    name: 'Infrastructure Deployment'
    uses: souzapablo/github-actions/.github/workflows/terraform.yml@main
    with:
      runners: '["ubuntu-latest", "windows-latest"]'  # Add more runners as needed: ["ubuntu-latest", "self-hosted", "windows-latest"]
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    permissions:  # explicitly pass allowed permissions
      contents: read
      pull-requests: write
