name: Deploy with Terraform

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  
jobs:
  deploy:
    uses: souzapablo/github-actions/.github/workflows/terraform-plan.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
 
