name: Deploy with Terraform
on:
  pull_request:
permissions:
  contents: read
  pull-requests: write
  
jobs:
  plan:
    uses: souzapablo/github-actions/.github/workflows/terraform-plan.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
  
  debug:
    needs: plan
    runs-on: ubuntu-latest
    steps:
      - name: Debug outputs
        run: |
          echo "has-changes output: '${{ terraform.plan.outputs.has-changes }}'"
          echo "plan-run-id output: '${{ terraform.plan.outputs.plan-run-id }}'"
          echo "has-changes type: $(echo '${{ needs.plan.outputs.has-changes }}' | wc -c)"
  
  apply:
    if: needs.plan.outputs.has-changes == 'true'
    needs: plan
    uses: souzapablo/github-actions/.github/workflows/terraform-apply.yml@main
    secrets:
      DO_TOKEN: ${{ secrets.DO_TOKEN }}
    with:
      plan_run_id: ${{ terraform.plan.outputs.plan-run-id }}
